name: Angular CICD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Bump version and push tag
        uses: ChloePlanet/github-tag-action@master
        id: tag-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor
          INITIAL_VERSION: 0.0.0

      - name: Docker Login
        uses: docker/login-action@v1.5.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build versioned and latest docker images
        run: docker-compose build
        env:
          VERSION_TAG: ${{ steps.tag-version.outputs.new_tag }}

      - name: Push versioned and latest docker images
        run: docker-compose push
        env:
          VERSION_TAG: ${{ steps.tag-version.outputs.new_tag }}
